genevieve_client/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path


from .views import (AuthorizeGennotesView,
                    AuthorizeOpenHumansView,
                    DeleteAccountView,
                    HomeView,
                    GenomeImportView,
                    GenomeReportDetailView,
                    GenomeReportListView,
                    GenomeReportReprocessView,
                    GenevieveNotesEditView,
                    ManageAccountView,
                    PublicGenomeReportListView)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path(r'about/',
         HomeView.as_view(template_name='genevieve_client/about.html'),
         name='about'),
    path(r'about_notes/',
         HomeView.as_view(template_name='genevieve_client/about_notes.html'),
         name='about_notes'),
    path('terms/',
         HomeView.as_view(template_name='genevieve_client/terms.html'),
         name='terms'),

    path('public_reports/',
         PublicGenomeReportListView.as_view(),
         name='public_reports'),

    path('genome_import/', GenomeImportView.as_view(), name='genome_import'),

    path('genome_reports/', GenomeReportListView.as_view(),
         name='genome_report_list'),
    re_path('genome_report/reprocess/(?P<pk>[0-9]+)/',
         GenomeReportReprocessView.as_view(),
         name='genome_report_reprocess'),
    re_path('genome_report/(?P<pk>[0-9]+)/', GenomeReportDetailView.as_view(),
         name='genome_report_detail'),

    re_path('notes/(?P<pk>[0-9]+)/(?P<relid>[0-9]+)/',
         GenevieveNotesEditView.as_view(),
         name='notes_edit'),

    path('authorize_gennotes/', AuthorizeGennotesView.as_view(),
         name='authorize_gennotes'),
    path(r'authorize_openhumans/', AuthorizeOpenHumansView.as_view(),
         name='authorize_openhumans'),

    path('admin/', admin.site.urls),

    # django-allauth URLs
    path(r'accounts/', include('allauth.urls')),

    # Account management
    path('manage_account/',
         ManageAccountView.as_view(),
         name='manage_account'),
    path('delete_account/', DeleteAccountView.as_view(),
         name='delete_account'),
]

genevieve_client/models.py
from collections import OrderedDict
import datetime
import re
import requests

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils import timezone as django_timezone

from pytz import timezone as pytz_timezone
import myvariant
from vcf2clinvar import clinvar_update


CHROMOSOMES = OrderedDict([
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, '7'),
    (8, '8'),
    (9, '9'),
    (10, '10'),
    (11, '11'),
    (12, '12'),
    (13, '13'),
    (14, '14'),
    (15, '15'),
    (16, '16'),
    (17, '17'),
    (18, '18'),
    (19, '19'),
    (20, '20'),
    (21, '21'),
    (22, '22'),
    (23, 'X'),
    (24, 'Y'),
    (25, 'MT'),
    ])


class Variant(models.Model):
    chromosome = models.PositiveSmallIntegerField(choices=CHROMOSOMES.items())
    pos = models.PositiveIntegerField()
    ref_allele = models.CharField(max_length=255)
    var_allele = models.CharField(max_length=255)

    myvariant_clinvar = JSONField(default=dict)
    myvariant_exac = JSONField(default=dict)
    myvariant_dbsnp = JSONField(default=dict)
    myvariant_gnomad_genome = JSONField(default=dict)
    myvariant_last_update = models.DateTimeField(null=True)

    def __unicode__(self):
        return self.b37_id

    @property
    def allele_frequency(self):
        if self.myvariant_gnomad_genome:
            return float(self.myvariant_gnomad_genome['af']['af'])
        elif self.myvariant_exac:
            ac = None
            if type(self.myvariant_exac['alleles']) == list:
                try:
                    idx = self.myvariant_exac['alleles'].index(self.var_allele)
                    ac = self.myvariant_exac['ac']['ac'][idx]
                except Exception:
                    pass
            else:
                ac = self.myvariant_exac['ac']['ac']
            if ac:
                an = self.myvariant_exac['an']['an']
                return ac * 1.0 / an
        elif self.myvariant_dbsnp:
            if 'alleles' not in self.myvariant_dbsnp:
                return None
            if type(self.myvariant_dbsnp['alleles']) == list:
                for item in self.myvariant_dbsnp['alleles']:
                    try:
                        if item['allele'] == self.var_allele:
                            return item['freq']['topmed']
                    except KeyError:
                        continue
            else:
                return self.myvariant_dbsnp['alleles']['freq']['topmed']
        return None

    @property
    def b37_id(self):
        return '-'.join([str(x) for x in [self.chromosome, self.pos,
                                          self.ref_allele, self.var_allele]])

    @property
    def b37_exac_id(self):
        return '-'.join([str(x) for x in [
            self.get_chromosome_display(), self.pos,
            self.ref_allele, self.var_allele]])

    @property
    def b37_hgvs_id(self):
        return myvariant.format_hgvs(
            self.get_chromosome_display(),
            self.pos,
            self.ref_allele,
            self.var_allele
        )

    @property
    def b37_gennotes_id(self):
        return 'b37-{}-{}-{}-{}'.format(
            self.chromosome, self.pos, self.ref_allele, self.var_allele)


class GenomeReport(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    report_name = models.CharField(max_length=120)
    genome_file_url = models.TextField()
    genome_file_created = models.TextField()
    last_processed = models.DateTimeField(null=True)
    report_source = models.CharField(max_length=80, blank=True)
    variants = models.ManyToManyField(Variant, through='GenomeVariant',
                                      through_fields=('genome', 'variant'))

    def refresh_myvariant_data(self):
        vars_by_hgvs = {
            v.b37_hgvs_id: v for v in self.variants.all()}
        mv = myvariant.MyVariantInfo()
        mv_data = mv.getvariants(vars_by_hgvs.keys(), fields=[
            'clinvar', 'dbsnp', 'exac', 'gnomad_genome'])
        for var_data in mv_data:
            if '_id' not in var_data:
                variant = vars_by_hgvs[var_data['query']]
                variant.myvariant_clinvar = dict()
                variant.myvariant_exac = dict()
                variant.myvariant_dbsnp = dict()
                variant.save()
                continue
            variant = vars_by_hgvs[var_data['_id']]
            try:
                clinvar_data = var_data['clinvar']
                # Always as list - makes downstream code much easier.
                if not type(clinvar_data['rcv']) == list:
                    clinvar_data['rcv'] = [clinvar_data['rcv']]
                variant.myvariant_clinvar = var_data['clinvar']
            except KeyError:
                variant.myvariant_clivar = dict()
            try:
                variant.myvariant_exac = var_data['exac']
            except KeyError:
                variant.myvariant_exac = dict()
            try:
                variant.myvariant_dbsnp = var_data['dbsnp']
            except KeyError:
                variant.myvariant_dbsnp = dict()
            try:
                variant.myvariant_gnomad_genome = var_data['gnomad_genome']
            except KeyError:
                variant.myvariant_gnomad_genome = dict()
            variant.myvariant_last_update = django_timezone.now()
            variant.save()

    def new_clinvar_available(self):
        cv_year, cv_month, cv_day = [int(x) for x in re.search(
            r'_(20[0-9][0-9])([01][0-9])([0-3][0-9])\.vcf',
            clinvar_update.latest_vcf_filename('b37')).groups()]
        try:
            cv_latest = datetime.datetime(
                cv_year, cv_month, cv_day + 1, 0, 0, 0,
                tzinfo=pytz_timezone('US/Eastern'))
        except ValueError:
            try:
                cv_latest = datetime.datetime(
                    cv_year, cv_month + 1, 1, 0, 0, 0,
                    tzinfo=pytz_timezone('US/Eastern'))
            except ValueError:
                cv_latest = datetime.datetime(
                    cv_year + 1, 1, 1, 0, 0, 0,
                    tzinfo=pytz_timezone('US/Eastern'))
        if self.last_processed and self.last_processed > cv_latest:
            return False
        return True

    def refresh_oh_report_file_url(self, user_data=None):
        if self.report_source.startswith('openhumans-'):
            new_url, created = self.user.openhumansuser.file_url_for_source(
                self.report_source, user_data=user_data)
            if new_url:
                self.genome_file_url = new_url
                # Changed creation indicates a fresh file for processing.
                if created != self.genome_file_created:
                    self.genome_file_created = created
                    self.last_processed = None
                self.save()

    def refresh(self, oh_user_data=None, force=False):
        if self.new_clinvar_available() or force:
            # Refresh file URL for Open Humans data.
            if self.report_source.startswith('openhumans-'):
                self.refresh_oh_report_file_url(user_data=oh_user_data)

            # Refresh object to ensure up-to-date file URL.
            report = GenomeReport.objects.get(pk=self.pk)

            # Avoid circular import.
            from .tasks import produce_genome_report

            # Delete old variants and create a new list.
            report.genomevariant_set.all().delete()
            produce_genome_report.delay(report.id)
        else:
            from .tasks import refresh_myvariant_data
            refresh_myvariant_data.delay(self.id)


class GenomeVariant(models.Model):
    genome = models.ForeignKey(GenomeReport, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    zygosity = models.CharField(max_length=3,
                                choices=(('Het', 'Heterozygous'),
                                         ('Hom', 'Homozygous'),
                                         ('Hem', 'Hemizygous')))


class GenevieveUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    genome_upload_enabled = models.BooleanField(default=False)
    passed_quiz = models.BooleanField(default=False)
    agreed_to_terms = models.BooleanField(default=False)


class ConnectedUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    access_token = models.CharField(max_length=30, blank=True)
    refresh_token = models.CharField(max_length=30, blank=True)
    token_expiration = models.DateTimeField(null=True)
    connected_id = models.CharField(null=False, max_length=30, unique=True)

    class Meta:
        abstract = True

    def _refresh_tokens(self):
        response_refresh = requests.post(
            self.TOKEN_URL,
            data={
                'grant_type': 'refresh_token',
                'refresh_token': self.refresh_token},
            auth=requests.auth.HTTPBasicAuth(
                self.CLIENT_ID, self.CLIENT_SECRET))
        token_data = response_refresh.json()
        self.access_token = token_data['access_token']
        self.refresh_token = token_data['refresh_token']
        self.token_expiration = (django_timezone.now() +
                                 datetime.timedelta(
                                     seconds=token_data['expires_in']))
        self.save()

    def _token_expired(self, offset=0):
        """
        True if token expired (or expires in offset seconds), otherwise False.
        """
        offset_expiration = (
            self.token_expiration - django_timezone.timedelta(seconds=offset))
        if django_timezone.now() >= offset_expiration:
            return True
        return False

    def get_access_token(self, offset=30):

genevieve_client/forms.py
from django import forms

from .models import GenomeReport

GENEVIEVE_EFFECT_CHOICES = (
    ('causal', 'Causes this trait or disease'),
    ('risk_factor', 'Increased risk of this trait or disease'),
    ('protective', 'Prevents or reduces risk of this trait or disease'),
)

GENEVIEVE_INHERITANCE_CHOICES = (
    ('recessive', 'Recessive'),
    ('dominant', 'Dominant'),
    ('additive', 'Additive'),
    ('unknown', 'Other, unknown, or not applicable'),
)

GENEVIEVE_EVIDENCE_CHOICES = (
    ('well_established', 'Well-established'),
    ('reported', 'Reported'),
    ('contradicted', 'Contradicted'),
)


class GenomeUploadForm(forms.ModelForm):
    """
    Genome file upload form.
    """
    class Meta:
        model = GenomeReport
        fields = ['report_name', 'genome_file_url']
        widgets = {
            'genome_file_url': forms.Textarea(attrs={'cols': 80, 'rows': 1}),
        }

genevieve_client/templates/genevieve_client/about.html
{% extends 'base.html' %}


{% block content %}

{% include 'genevieve_client/partial_about.html' %}

<h3>Terms of Use</h3>

The <a href="{% url 'terms' %}">Terms of Use</a> must be agreed to by users of
Genevieve.

<h3>Contact us</h3>

<p style="margin-bottom:40px;">
  Please contact gennotes@gmail.com with questions regarding Genevieve.
</p>

{% endblock %}

genevieve_client/templates/genevieve_client/delete_account.html
{% extends 'base.html' %}


{% block content %}

<h2>Confirm account deletion?</h2>

<p class="lead">
  Deleting your account will delete any associated genome report(s).
</p>

<form action="{% url 'delete_account' %}" method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger" style="margin-bottom:15px;">
    Delete account and associated genome reports</button>
</form>
{% endblock %}

genevieve_client/templates/genevieve_client/genomereport_detail.html
{% extends 'base.html' %}
{% load report_tags %}

{% block js_scripts %}
<script src="/static/js/genomereport_detail.js"></script>
{% endblock js_scripts %}

{% block head_title %}{{ genomereport.report_name }}{% endblock %}

{% block content %}
<h2 id="report-name">{{ genomereport.report_name }}</h2>

{% if genomereport.user == request.user %}
<a class='btn btn-default btn-sm pull-right' href="{% url 'genome_report_reprocess' genomereport.id %}">Reprocess genome</a>
{% endif %}

{% if not report_rows %}
<div class="panel panel-primary">
  <div class="panel-heading">Genome report not yet complete.</div>
  <div class="panel-body">
    This report currently has no data. If this report is new or recently
    refreshed, it's probably still in processing. You'll need to reload this
    page to check if it's complete. Please give reports up to fifteen minutes.
  </div>
</div>
{% else %}
<form>
  <div class="checkbox">
    <label>
      <input id="report-filter-contradicted" type="checkbox"
       name="report-filter" checked> Hide contradicted effects
    </label>
  </div>
</form>
{% endif %}

<table id="genome-report" class="table" style="table-layout:fixed">
  <thead>
    <tr>
      <th style="width:180px;word-wrap:break-word;">Variant</th>
      <th width="100px">Allele Freq</th>
      <th>Info</th>
    </tr>
  </thead>

  <tbody>
  {% for row_data in report_rows %}
  <tr class="gv-row {{ row_data|variant_flags }}" id="gv-b37-{{ row_data.variant.b37_id }}">
    <td class="gv-id-cell" style="width:150px;word-wrap:break-word;">
      <p>
        {{ row_data.variant.b37_hgvs_id }}
      </p>
      {% if row_data.variant.myvariant_clinvar %}
        <p><small><b>ClinVar:</b> <a href="https://www.ncbi.nlm.nih.gov/clinvar/variation/{{ row_data.variant.myvariant_clinvar.variant_id }}/">
          {{ row_data.variant.myvariant_clinvar.rcv.0.preferred_name|space_after_colon }}
        </a></small></p>
      {% endif %}
      <p>{{ row_data.genome_variant.get_zygosity_display }}</p>
    </td>
    <td class="gv-freq-cell">
      {% if row_data.variant.myvariant_gnomad_genome %}
      <a href="http://gnomad.broadinstitute.org/variant/{{ row_data.variant.b37_exac_id }}">{{ row_data.variant.allele_frequency|floatformat:'-6' }}</a>
      {% elif row_data.variant.myvariant_exac %}
      <a href="http://exac.broadinstitute.org/variant/{{ row_data.variant.b37_exac_id }}">{{ row_data.variant.allele_frequency|floatformat:'-6' }}</a>
      {% else %}
        {% if row_data.variant.allele_frequency %}
        {{ row_data.variant.allele_frequency|floatformat:'-6' }}
        {% else %}
        Unknown
        {% endif %}
      {% endif %}
    </td>
    <td id="{{ gv.variant.id }}" class="gv-info-cell">
      {% for item in row_data.gennotes_data %}
        <div class="panel panel-info {{ item|note_flags }}">
          <div class="panel-body">
            <table>
              <tbody>
                <tr>
                  <th style="width:120px;">
                    {% if item.tags.category == 'disease' %}
                      Disease:
                    {% else %}Trait:{% endif %}
                  </th>
                  <td> {{ item.tags.name }}</td>
                </tr>
                <tr>
                  <th>
                    Inheritance:
                  </th>
                  <td>{{ item.tags.inheritance|inheritance_display }}</td>
                </tr>
                <tr>
                  <th>Significance:</th>
                  <td>{{ item.tags.significance|significance_display }}</td>
                </tr>
                <tr>
                  <th>Evidence:</th>
                  <td>{{ item.tags.evidence }}</td>
                </tr>
                {% if item.tags.clinvar_rcv_records %}
                <tr>
                  <th>Clinvar records:</th>
                  <td>
                  {% for rcv, rcv_data in item.tags.clinvar_rcv_records.items %}
                    {{ rcv_data.clinical_significance }}:
                    <a href="https://www.ncbi.nlm.nih.gov/clinvar/{{ rcv_data.accession }}/">
                      {{ rcv_data.conditions.name }}</a></br>
                  {% endfor %}
                  </td>
                </tr>
                {% endif %}
                <tr>
                  <th>Notes:</th>
                  <td>
                    <p>{{ item.tags.notes|markdown }}</p>
                  </td>
                </tr>
              </tbody>
            </table>
            <a href="https://gennotes.herokuapp.com/genevieve-effect/{{ item.relation_id }}">View/edit on GenNotes</a>
          </div>
        </div>
      {% endfor %}
      {% if row_data.unclaimed_rcvs %}
        <b>Clinvar entries without associated notes:</b>
        <ul>
          {% for rcv, rcv_data in row_data.unclaimed_rcvs.items %}
          <li>
            {{ rcv_data.clinical_significance }}:
            <a href="https://www.ncbi.nlm.nih.gov/clinvar/{{ rcv_data.accession }}/">
              {{ rcv_data.conditions.name }}</a>
          </li>
          {% endfor %}
        </ul>
        {% if not row_data.gennotes_data %}
          <span class="pull-right">
            <a href="https://gennotes.herokuapp.com/genevieve-edit/?build=b37&amp;chrom={{ row_data.variant.chromosome }}&amp;pos={{ row_data.variant.pos }}&amp;ref_allele={{ row_data.variant.ref_allele }}&amp;var_allele={{ row_data.variant.var_allele }}">Add effect notes to GenNotes</a>
          </span>
        {% endif %}
      {% endif %}
      <p>
        {% if request.user.gennoteseditor %}
        <a href="{% url 'notes_edit' row_data.variant.id 0 %}?report={{ genomereport.id }}"
          class="btn btn-xs btn-default">Create notes for a new effect</a>
        {% endif %}
      </p>
    </td>
  </tr>
  {% endfor %}
  </tbody>

</table>
{% endblock content %}


{% block js_templates %}
<!-- Display of retrieved ReferenceClinVarAssertion data from GenNotes -->
<script type="text/template" id="variant-id-template">
  <p>
    <b>${ b37VariantID }</b>
  </p>
  <p>
    <small><b>ClinVar name: </b>${ clinvarRCVAPreferredName }</small>
  </p>
  <p>
    <small><a href="${ linkGETEvidence }">Check on GET-Evidence</a></small>
  </p>
</script>

<script type="text/template" id="variant-freq-template">
  ${ clinvarRCVAfreqESP }<br>
  <small><a href="${ linkExAC }">Check on ExAC</a></small>
</script>

<script type="text/template" id="variant-info-template">
  <div class="row">
    <div class="col-xs-4">
      <b><a href="http://www.ncbi.nlm.nih.gov/clinvar/${ clinvarRCVAAccession }">
        ${ clinvarRCVAAccession }</a></b>
      <ul style="padding-left:15px;">
        <li><b>${ clinvarTraitLabel }: </b>${ clinvarRCVADiseaseName }</li>
        <li><b>Significance: </b>${ clinvarRCVASignificance }</li>
      </ul>
    </div>
    <div class="col-xs-8">
      <b>Genevieve information</b>
      <ul class="genevieve-information" style="padding-left:15px;">
        <li><b>Inheritance: </b>${ genevieveInheritance }</li>
        <li><b>Evidence: </b>${ genevieveEvidence }</li>
        <li><b>Notes: </b>${ genevieveNotes }</li>
      </ul>
      <a href="/variant/${ localVariantID }/">View/add/update shared notes</a>
    </div>
  </div>
</script>
{% endblock js_templates %}

genevieve_client/templates/genevieve_client/genomereport_list.html
{% extends 'base.html' %}

{% block content %}

<h2>Your genome reports</h2>

<table class="table">
  <tr>
    <th>Report name</th>
    <th>Genome format</th>
  </tr>

  {% for report in genomereport_list %}
  <tr>
    <td><a href="{% url 'genome_report_detail' report.pk %}">
      {{ report.report_name }}</a></td>
    <td>{{ report.get_genome_format_display }}</td>
  </tr>
  {% endfor %}

</table>

{% endblock %}

genevieve_client/templates/genevieve_client/home.html
{% extends 'base.html' %}


{% block content %}
<h1>Genevieve</h1>

{% if user.is_authenticated and not user.genevieveuser.agreed_to_terms %}
<h2>Please read and agree to the following.</h2>
<p>
  Before Genevieve creates reports, I need to make sure you understand
  what Genevieve is &ndash; and isn't.
</p>

{% include 'genevieve_client/partial_about_intro.html' %}

{% include 'genevieve_client/partial_education_and_exploration.html' %}

{% include 'genevieve_client/partial_contains_errors.html' %}

{% include 'genevieve_client/partial_public_reports.html' %}

<hr>
<p>
  <b>Please show you understand by answering the following questions.</b>
</p>
<p>
  <form action="{% url 'home' %}" method="post">
    {% csrf_token %}
    <p>
      <h4>What is Genevieve's intended use?</h4>
      <div class="radio">
        <label><input type="radio" name="intended_use" value="clinical">Clinical interpretation.</label>
      </div>
      <div class="radio">
        <label><input type="radio" name="intended_use" value="educational">Personal exploration and education.</label>
      </div>
    </p>
    <p>
      <h4>Is Genevieve accurate?</h4>
      <div class="radio">
        <label><input type="radio" name="accurate" value="no">No. Genevieve will contain errors. Many reported effects will be incorrect.</label>
      </div>
      <div class="radio">
        <label><input type="radio" name="accurate" value="yes">Yes. Genevieve ensures high quality through expert review.</label>
      </div>
    </p>
    <p>
      <h4>Is Genevieve comprehensive?</h4>
      <div class="radio">
        <label><input type="radio" name="comprehensive" value="no">No, Genevieve may fail to highlight information I consider important.</label>
      </div>
      <div class="radio">
        <label><input type="radio" name="comprehensive" value="yes">Yes, Genevieve will discover and report all important variants in a data set.</label>
      </div>
    </p>

    <p>
      <h4>Will your Genevieve report always be private?</h4>
      <div class="radio">
        <label><input type="radio" name="private" value="yes">Yes. All Genevieve reports are private.</input></label>
      </div>
      <div class="radio">
        <label><input type="radio" name="private" value="depends">Only if my genetic data is private in Open Humans. If my genetic data is public on Open Humans, my Genevieve report will also be publicly shared.</label>
      </div>
    </p>

    <hr>
    <div class="checkbox" style="margin-bottom:15px;">
      <label>
        <input type="checkbox" name="terms">
        I agree to the Genevieve
        <a href="{% url 'terms' %}">terms of use</a.
      </label>
    </div>

    <button type="submit" class="btn btn-primary" style="margin-bottom:15px;">
      Continue</button>
  </form>
</p>
{% endif %}

{% if user.is_authenticated and user.genevieveuser.agreed_to_terms %}
  <h2>Your genome reports</h2>

  {% if genomereport_list %}
  <table class="table">
    <thead>
    <tr>
      <th>Report name</th>
    </tr>
  </thead>

  <tbody>
    {% for report in genomereport_list %}
    <tr>
      <td><a href="{% url 'genome_report_detail' report.pk %}">
        {{ report.report_name }}</a></td>
    </tr>
    {% endfor %}
  </tbody>
  </table>

  {% else %}
  <p>
    Sorry! It seems like there are no qualifying data sets to generate reports.
  </p>

  <p>
    Genevieve is only available for data in Open Humans from
    the following activities: 23andMe, Harvard PGP, and Genome/Exome Data.
  </p>
  {% endif %}

<hr>
<div class="alert alert-warning" role="alert">
  <p>
    <b>Have you updated data in Open Humans?</b>
    When you update data in Open Humans, you need to go to
    <a href="{% url 'manage_account' %}">your Genevieve account management
    page</a> and trigger data refresh &amp; reprocessing if you want to
    see updated reports.
  </p>
</div>
{% endif %}

{% if user.is_authenticated and not user.openhumansuser and user.gennoteseditor and user.genevieveuser.agreed_to_terms%}
  <p>
    <b>You're logged in with the following GenNotes account.</b> Edits to
    variant notes you make will be submitted to this account. Edits are
    publicly shared and associated with this username. However, your email
    will remain private, only available to administrators of GenNotes and this
    Genevieve site.
  </p>
  <div class="well well-sm" style="margin-left:20px;margin-bottom:15px;display:inline-block;">
    <b>Username:</b> {{ request.user.gennoteseditor.gennotes_username }}<br>
    <b>Email:</b> {{ request.user.gennoteseditor.gennotes_email }}
  </div>
  <p>
    Wrong account? Make sure you're logged in to the correct account on
    <a href="{{ gennotes_server }}">GenNotes</a>. Once this is corrected, you
    can <a href="{% url 'account_logout' %}">log out</a> and back in again on
    this Genevieve site.
  </p>
  <hr>
{% endif %}

{% if request.user.genevieveuser.genome_upload_enabled and user.genevieveuser.agreed_to_terms %}
<p><a href="{% url 'genome_import' %}" class='btn btn-primary'>
  Import genome</a></p>
<p>
  Import a genome to create a private report. Genome data must be formatted
  as VCF or gVCF, build 37.
</p>
<hr>
{% endif %}

{% if not user.is_authenticated or not user.openhumansuser %}
  <h3>Connect Open Humans</h3>
  <p>
    Connect an <a href="{{ openhumans_url }}">Open Humans</a> account to enable
    Genevieve to automatically create reports from the genetic data you've
    added to Open Humans.
  </p>
  {% if not user.is_authenticated %}
  <p>
    Already connected? The button below will log you back in.
  </p>
  {% endif %}

  <a href="{{ openhumans_auth_url }}" class='btn btn-primary btn-lg'>
      Connect Open Humans</a>

  <hr>
{% endif %}

{% if not user.is_authenticated %}

{% include 'genevieve_client/partial_about.html' %}

<h3>Can I contribute notes without connecting Open Humans?</h3>
<p>
  Even if you aren't interested in generating a report from your own genetic
  data, I hope you consider connecting via Open Humans. It's a fun community,
  and you're also welcome to join <a href="http://slackin.openhumans.org/">our
  community Slack</a> to chat!
</p>
<p>
  But if joining as an Open Humans member isn't an option, you can log in
  directly with an authorized <a href="{{ gennotes_url }}">GenNotes</a> account.
  <a href="{{ gennotes_signup_url }}">Create a GenNotes account</a> if
  you don't already have one. Then use the button below to authorize notes
  submissions and log in to Genevieve.
</p>
<a href="{{ gennotes_auth_url }}" class='btn btn-default btn-xs'
    style="margin-bottom:20px;">
  Log in with a GenNotes account</a>
{% endif %}

{% endblock %}